### ISSUE TITLE
403 on thumbnail.

### ISSUE THREAD

**Issue by tylerjfields** [emerald-co/emeraldchat.com#11]
https://emerald-s3.s3.amazonaws.com/uploads/picture/image/63080/thumb_MisterWolf.jpeg shows as forbidden (403)

Triggered by clicking messages notifications ( maybe related to MightyMouse's profile. )

**Comment by tylerjfields** [comment]
This seems to also happen while viewing other pages, not so sure it has to do with MightyMouse's profile, but the only "wolf" i found in source is the wolf emoji. Perhaps related?

**Comment by tylerjfields** [comment]
Tracked it down: 

    `     <img src="https://emerald-s3.s3.amazonaws.com/uploads/picture/image/63080/thumb_MisterWolf.jpeg" alt="Display Picture" class="avatar-pico">`

**Comment by emerald-co** [comment]
Our DNS Cloudflare have a hotlink prevention mechanism that is probably the source of this.

Hope this helps. I am going to close this issue. Thanks for raising it though :)
