### ISSUE TITLE
Messages appear in notifications but do not appear when opened.

### ISSUE THREAD

**Issue by HikariAkiha** [emerald-co/emeraldchat.com#15]
You will get some messages but sometimes it will not receive a message after you connect. You won't know it exists unless you check your notifications and will reappear when you reload

**Comment by emerald-co** [comment]
Thanks for raising this Yunna, it's being investigated

**Comment by emerald-co** [comment]
Notifications have been re-vamped, closing this issue as I haven't experienced the bug as of yet. Feel free to re-open or post a similar issue if it is found again.
